print ('Hello world!')
print ('What is your name? ')
user_name = input()
print ("It is nice to meet you, " + user_name)
print ('The length of your name is: ')
print (len(user_name))
print ('What is your age? ')
user_age = input()
print ('You will be ' + str(int(user_age) + 1) + ' next year.')